app/usuario/forms.py
#coding: utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, ValidationError, EqualTo
from app.models import Usuario

class LoginForm(FlaskForm):
    username = StringField('Nickname', validators=[DataRequired()])
    password = PasswordField('Senha', validators=[DataRequired()])
    remember_me = BooleanField('Lembrar-me')
    submit = SubmitField('Fazer login')

class RegisterForm(FlaskForm):
    username = StringField('Nickname', validators=[DataRequired()])
    password = PasswordField('Senha', validators=[DataRequired()])
    password2 = PasswordField(
         'Repita a senha', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Registrar')

    def validate_username(self, username):
        user = Usuario.query.filter_by(nickname=username.data).first()
        if user is not None:
            raise ValidationError('Por favor, insira outro nickname')

app/usuario/__init__.py
from flask import Blueprint

bp = Blueprint('usuario', __name__)

from app.usuario import routes

app/usuario/routes.py
#coding: utf-8
from flask import render_template, flash, request, redirect, url_for
from app import db
from app.usuario import bp
from app.usuario.forms import LoginForm, RegisterForm
from flask_login import current_user, login_user, logout_user, login_required
from app.models import Usuario
from werkzeug.urls import url_parse


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        usuario = Usuario.query.filter_by(nickname=form.username.data).first()
        if usuario is None or not usuario.check_password(form.password.data):
            flash('Nome de usuário ou senha inválidos!!!')
            return redirect(url_for('usuario.login'))
        login_user(usuario, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)
    return render_template('usuario/login.html', title='Login', form=form)

@bp.route('/registrar', methods=['GET', 'POST'])
def registrar():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        usuario = Usuario(nickname=form.username.data, senha=form.password.data)
        usuario.set_password()
        db.session.add(usuario)
        db.session.commit()
        usuario = Usuario.query.filter_by(nickname=form.username.data).first()
        login_user(usuario)
        return redirect(url_for('main.index'))
    return render_template('usuario/registrar.html', title="Registrar", form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('usuario.login'))

app/templates/usuario/login.html
{% extends "main/base.html" %}

{% block conteudo %}
	<div>
		<h1>Login</h1>
		<p><a href="{{ url_for('usuario.registrar') }}">Ainda não tem uma conta? Registre-se!</a></p>
		<form action="" method="post" novalidate>
			{{ form.hidden_tag() }}
			<p>
				{{ form.username.label }}<br>
				{{ form.username(size=32) }}<br>
				{% for error in form.username.errors %}
				<span style="color:black">[{{ error }}]</span>
				{% endfor %}
			</p>
			<p>
				{{ form.password.label }}<br>
				{{ form.password(size=32) }}<br>
				{% for error in form.username.errors %}
				<span style="color:black">[{{ error }}]</span>
				{% endfor %}
			</p>
			<p><label>{{ form.remember_me() }} <span>{{ form.remember_me.label }}</span></label></p>
            <button class="btn waves-effect waves-light red darken-4" type="submit" name="action">Login
                <i class="material-icons right">send</i>
            </button>
		</form>
	</div>
{% endblock%}

app/templates/usuario/registrar.html
{% extends "main/base.html" %}


{% block conteudo %}
	<div>
    	<h1>Registrar</h1>
    	<form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <p>
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}<br>
        	    {% for error in form.username.errors %}
    	    <span style="color:black">[{{ error }}]</span>
    	    {% endfor %}
            </p>
            <p>
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}<br>
    	    {% for error in form.password.errors %}
                <span style="color:black">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
    	    {{ form.password2.label }}<br>
                {{ form.password2(size=32) }}<br>
                {% for error in form.password2.errors %}
                <span style="color:black">[{{ error }}]</span>
                {% endfor %}
    	</p>
            <button class="btn waves-effect waves-light red darken-4" type="submit" name="action">Registrar
                <i class="material-icons right">send</i>
            </button>
    	</form>
	</div>
{% endblock%}