app/sala/forms.py
#coding: utf-8
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class SalaForm(FlaskForm):
    nome = StringField('Nome', validators=[DataRequired()])
    senha = PasswordField('Senha')
    submit = SubmitField('Criar')

class DeletarForm(FlaskForm):
    lista = SelectField('Selecione', coerce=int)
    submit = SubmitField('Deletar')

app/sala/__init__.py
from flask import Blueprint

bp = Blueprint('sala', __name__)

from app.sala import routes

app/sala/routes.py
#coding: utf-8
from flask import render_template, flash, jsonify, request, redirect, url_for
from app import app, db
from app.sala import bp
from app.sala.forms import SalaForm, DeletarForm
from flask_login import current_user, login_required
from app.models import Usuario, Mensagem, Categoria, Sala


@bp.route('/Sala/<id_sala>/<nome_sala>', methods=['GET', 'POST'])
@login_required
def sala(id_sala, nome_sala):
    if not Sala.query.filter_by(id=id_sala).first():
        flash('Esta sala não existe!')
        return redirect(url_for('main.index'))
    try:
        id = Mensagem.query.order_by(Mensagem.id.desc()).first().id
    except:
        id = 0

    sala = Sala.query.filter_by(id=id_sala).first()
    #Verifica se o usuário está banido da sala
    if(not current_user.admin and sala.isBanido(current_user.id)):
        flash('Você está banido desta sala!')
        return redirect(url_for('main.index'))

    #Verifica se o usuário é admin do site ou dono da sala
    if(not current_user.admin and current_user.id != sala.admin_id):
        #Verifica se há senha ou se a senha está correta
        if(sala.senha and not sala.check_password(request.form.get('senha', ''))):
            flash('Senha incorreta!')
            return redirect(url_for('sala.senha_sala', sala_id=sala.id, sala_nome=sala.nome))

    user = Usuario()
    usuario_atual = user.query.filter_by(id=current_user.id).first()
    #Adiciona o usuário à sala
    usuario_atual.join_sala(sala)
    db.session.commit()
    #Pega as 10 últimas conversas
    conversas = Mensagem.query.filter(Mensagem.sala_id==id_sala).order_by(Mensagem.data_envio.desc()).limit(10)
    #Inverte a ordem das conversas
    conversas = conversas[::-1]
    return render_template('sala/sala.html', title='Sala', sala=sala, id_inicial=id, \
        id_sala=id_sala, conversas=conversas, user=user)


@bp.route('/Sala/Banir', methods=['POST'])
@login_required
def banir():
    sala_id = request.form['sala_id']
    usuario_id = request.form['usuario_id']
    if(not sala_id and not usuario_id):
        return 'fail'
    sala = Sala.query.filter_by(id=sala_id).first()
    usuario = Usuario.query.filter_by(id=usuario_id).first()

    if (not sala or not usuario):
        return 'fail'

    if(current_user.id != sala.admin_id and not current_user.admin):
        return 'fail'

    sala.banir(usuario)
    db.session.commit()
    return 'success'

@bp.route('/Sala/Senha/<sala_id>/<sala_nome>', methods=['GET', 'POST'])
@login_required
def senha_sala(sala_id, sala_nome):
    return render_template('sala/senha_sala.html', title='Senha', sala_id=sala_id, sala_nome=sala_nome)


@bp.route('/Sala/Desbanir', methods=['POST'])
@login_required
def desbanir():
    sala_id = request.form['sala_id']
    usuario_id = request.form['usuario_id']
    if(not sala_id and not usuario_id):
        return 'fail'
    sala = Sala.query.filter_by(id=sala_id).first()

    if (not sala):
        return 'fail'

    sala.desbanir(usuario_id)
    db.session.commit()
    return 'success'


@bp.route('/Sala/Listar/Banidos/<sala_id>', methods=['GET'])
@login_required
def get_banidos(sala_id):
    sala = Sala.query.filter_by(id=sala_id).first()
    if (not sala):
        return jsonify({"msg":"Esta sala não existe!"})

    if (not current_user.admin and current_user.id!=sala.admin_id):
        return jsonify({"msg":"Você não está autorizado!"})
    
    banidos = sala.banidos.all()
    i=0
    for assoc in banidos[:]:
        dicionario = {}
        dicionario['id'] = assoc.banido.id
        dicionario['nickname'] = assoc.banido.nickname
        banidos[i] = dicionario
        i+=1
    return jsonify({"banidos":banidos})


@bp.route('/Sala/Sair/<id_sala>')
@login_required
def sair_sala(id_sala):
    usuario = Usuario.query.filter_by(id=current_user.id).first()
    usuario.leave_sala(id_sala)
    db.session.commit()
    flash('Você saiu da sala!')
    return redirect(url_for('main.index'))


@bp.route('/Sala/Cadastro/<categoria>/<cat_nome>', methods=['GET', 'POST'])
@login_required
def cad_sala(categoria, cat_nome):
    if not Categoria.query.filter_by(id=categoria).first():
        flash('A categoria selecionada não existe!')
        return redirect(url_for('main.index'))
    form = SalaForm()
    if form.validate_on_submit():
        nome_categoria = Categoria.query.filter_by(id=categoria).first().nome
        if not nome_categoria:
            flash('A categoria selecionada não existe!')
            return redirect(url_for('main.index'))
        sala = Sala(nome=form.nome.data, categoria_id=categoria, admin_id=current_user.id, senha=form.senha.data)
        if(form.senha.data):
            sala.set_password()
        db.session.add(sala)
        db.session.commit()
        flash('Sala criada com sucesso na categoria %s!' % nome_categoria)
        return redirect(url_for('main.index'))
    return render_template('sala/cad_sala.html', title='Cadastrar Sala', form=form, cat_nome=cat_nome)


@bp.route('/Sala/Deletar', methods=['GET', 'POST'])
@login_required
def del_sala():
    form = DeletarForm()
    if(not current_user.admin):
        salas = Sala.query.filter_by(admin_id=current_user.id).all()
    else:
        salas = Sala.query.all()
    if not salas:
        flash('Você ainda não criou nenhuma sala :(')
        return redirect(url_for('main.index'))
    form.lista.choices = [(s.id, s.nome) for s in salas]
    if form.validate_on_submit():
        sala = Sala.query.filter_by(id=form.lista.data).first()
        if (sala.admin_id == current_user.id or current_user.admin):
            db.session.delete(sala)
            db.session.commit()
            flash('Sala %s removida com sucesso!' % sala.nome)
            return redirect(url_for('main.index'))
    return render_template('sala/del_sala.html', title='Deletar Salas', form=form)

app/templates/sala/cad_sala.html
{% extends "main/base.html" %}

{% block conteudo %}
	<div>
		<h3>Cadastro de Sala na Categoria {{ cat_nome }}</h3>
		<form action="" method="post" novalidate>
		{{ form.hidden_tag() }}
		<p>
			{{ form.nome.label }}<br>
			{{ form.nome(size=32) }}<br>
			{% for error in form.nome.errors%}
			<span style="color:black">[{{ error }}]</span>
			{% endfor %}
			{{ form.senha.label }}<br>
			{{ form.senha(size=32) }}<br>
			{% for error in form.senha.errors%}
			<span style="color:black">[{{ error }}]</span>
			{% endfor %}
		</p>
            <button class="btn waves-effect waves-light red darken-4" type="submit" name="action">Cadastrar
                <i class="material-icons right">send</i>
            </button>
		</form>
	</div>
{% endblock %}

app/templates/sala/del_sala.html
{% extends "main/base.html" %}

{% block conteudo %}
			<h3>Deletar sala</h3>
			<form action="" method="post" novalidate>
				{{ form.hidden_tag()}}
				<div class="input-field col s12">
					{{ form.lista }}
				</div>
		        <button class="btn waves-effect waves-light red darken-4" type="submit">Deletar
		            <i class="material-icons right">send</i>
				</button>
			</form>
{% endblock%}

app/templates/sala/sala.html
{% extends "main/base.html" %}


{% block conteudo %}
	<div class="row red darken-3">
		<div class="col s12" style="margin-bottom:3%">
		    <h1>Sala {{ sala.nome }}</h1>
			<a class="waves-effect waves-light btn red darken-4" href="{{ url_for('sala.sair_sala', id_sala=sala.id)}}">Sair da sala</a>
			{% if current_user.admin or current_user.id==sala.admin_id %}
			<a onclick="getBanidos()" class="waves-effect waves-light btn red darken-4" href="#lista_banidos" rel="modal:open">Ver lista de banidos</a>
			{% endif %}
		</div>
		<div id="main" class="col s8" style="height:70%;overflow:auto">
			{% for conversa in conversas %}
				{% if conversa.usuario_id == current_user.id %}
					<div class="msg_eu red darken-4"><p>{{ current_user.nickname }}: {{ conversa.conteudo }}</p></div>
				{% else %}
					{% if conversa.private_id %}
					{% if conversa.private_id == current_user.id %}
					<div class="msg_eles red lighten-1"><p>{{conversa.data_envio}} (reservadamente){{ conversa.remetente.nickname }}: {{ conversa.conteudo }}</p></div>
					{% endif %}
					{% else %}
					<div class="msg_eles red lighten-1"><p>{{conversa.data_envio}} {{ conversa.remetente.nickname }}: {{ conversa.conteudo }}</p></div>
					{% endif %}
				{% endif %}
			{% endfor %}
		</div>
		<div id="usuarios" class="col s4 center-align" style="height:70%;overflow:auto">
			<h5>Usuários</h5>
			<ul class="collection">
			{% for assoc in sala.usuarios %}
			<li class="collection-item center-align red darken-4"><p>{{ assoc.usuario.nickname }}</p></li>
			{% endfor %}
			</ul>
		</div>
		<div id="secretas" class="col s12" style="margin-top:3%;max-height: 5%;overflow:auto">
			<span>Enviar para: </span>
			<label>
				<input type="radio" name="msg_secreta" id="todos" value=""></input>
				<span>Todos</span>
			</label>
			{% for assoc in sala.usuarios %}
			<label>
				<input type="radio" name="msg_secreta" id="{{ assoc.usuario.nickname }}" value="{{ assoc.usuario.id}}"></input>
				<span>{{ assoc.usuario.nickname }}</span>
			</label>
			{% endfor %}
		</div>
		<div class="col s12">
			<div class="row">
				<div class="col s8">
					<input id="mensagem" type="text"></input>
				</div>
				<div class="col s4">
					<button id="send" class="btn waves-effect waves-light red darken-4" type="submit">Enviar
	                <i class="material-icons right">send</i>
	        		</button>
				</div>
		</div>
	</div>
	<div id="lista_banidos" class="modal">
	  <p>Carregando...</p>
	</div>
	<script src="/static/js/jquery.modal.min.js"></script>
	<link rel="stylesheet" href="/static/css/jquery.modal.min.css" />
	<script>
		id = {{ id_inicial }}
		pausado = false;
		csrf_token = "{{ csrf_token() }}";

	    $.ajaxSetup({
	        beforeSend: function(xhr, settings) {
	            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
	                xhr.setRequestHeader("X-CSRFToken", csrf_token);
	            }
	        }
	    });

		setInterval(function(){
			if(!pausado) {
				procurar(id);
			}
		}, 3000)

		setInterval(function(){
			atualizar_estado()
		}, 10000)

		$('#send').click(function(){
			mensagem = $('#mensagem').val()
			if (mensagem) {
				pausado = true
				procurar(id)
				secreta = $("input[name=msg_secreta]:checked").val()
				$.post('{{ url_for('main.enviar_mensagem') }}', {mensagem:$('#mensagem').val(), sala:{{ id_sala }}, secreta: secreta},
					function(data){
						$('#main').append('<div class="msg_eu red darken-4"><p>{{ current_user.nickname }}: '+mensagem+'</p></div>')
						id = data['id']
						$('#mensagem').val('')
					})
				pausado = false;
			}
		})

		//realiza a busca por mensagens e usuários
		function procurar(identificador) {
			$.post('{{ url_for('main.conversa') }}', {id:identificador, sala:{{ id_sala }}},

			function(data){
				if(data['resposta'] == 'B'){
					alert('VOCÊ FOI BANIDO!')
					window.location.replace("/")
				}
				mensagens = data['mensagens']
				usuarios = data['usuarios']
				id = data['id']

				usuarioshtml = '<h5>Usuários</h5><ul class="collection">'
				secretashtml = "<span>Enviar para: </span><label><input type='radio' name='msg_secreta' id='todos' value=''></input><span>Todos</span></label>"
				mensagenshtml = ''
				for (posicao in mensagens){
					if(mensagens[posicao].private_id){
						mensagenshtml += "<div class='msg_eles red lighten-1'><p>"+mensagens[posicao].data_envio+"(reservadamente)"+mensagens[posicao].remetente+": "+mensagens[posicao].conteudo+"</p></div>"
					}
					else{
						mensagenshtml += "<div class='msg_eles red lighten-1'><p>"+mensagens[posicao].data_envio+" "+mensagens[posicao].remetente+": "+mensagens[posicao].conteudo+"</p></div>"
					}
				}
				$('#main').append(mensagenshtml)


				for (posicao in usuarios){
					{% if current_user.admin or current_user.id==sala.admin_id %}
					usuarioshtml += '<li class="collection-item center-align red darken-4"><p>'+usuarios[posicao].nome+'&nbsp;&nbsp;<button class="waves-effect waves-light btn red darken-4" onclick="banir('+usuarios[posicao].id+')">BANIR</button></p></li>'
					{% else %}
					usuarioshtml += '<li class="collection-item center-align red darken-4"><p>'+usuarios[posicao].nome+'</p></li>'
					{% endif %}
					secretashtml += "<label><input type='radio' name='msg_secreta' id='"+usuarios[posicao].nome+"' value='"+usuarios[posicao].id+"'></input><span>"+usuarios[posicao].nome+"</span></label>"
				}

				atual = $('#usuarios').html()
				if (atual != (usuarioshtml+'</ul>')) {
					$('#usuarios').html(usuarioshtml+'</ul>')
					$('#secretas').html(secretashtml)
				}
			})
		}

        function atualizar_estado(){
			$.post('{{ url_for('main.update_usuario_sala') }}', {sala_id:{{ id_sala}}},function(data){console.log(data)})
		}

		{% if current_user.admin or current_user.id==sala.admin_id %}
		
		function banir(id_banido){
			$.post('{{ url_for('sala.banir') }}', {sala_id:{{ id_sala}}, usuario_id:id_banido},function(data){console.log(data)})
		}

		function desbanir(id_desbanido){
			$.post('{{ url_for('sala.desbanir') }}', {sala_id:{{ id_sala}}, usuario_id:id_desbanido},function(data){
			})

			$.modal.getCurrent().close();
		}

		function getBanidos(){
			$.get('{{ url_for("sala.get_banidos",sala_id=id_sala) }}', function(data){
				html_banidos = ""
				banidos = data['banidos']
				if( !banidos[0] ){
					$('#lista_banidos').html('<p>Não há usuários banidos nesta sala.</p>')
				}
				else{
					for (posicao in banidos) {
						html_banidos += "<p>"+banidos[posicao].nickname+" <button onclick='desbanir("+banidos[posicao].id+")'>DESBANIR</button></p>"
					}

					$('#lista_banidos').html(html_banidos)
				}
			})
		}
		{% endif %}
	</script>
{% endblock %}

app/templates/sala/senha_sala.html
{% extends "main/base.html" %}

{% block conteudo %}
	<div>
		<h3>Senha para a sala {{ sala_nome }}</h3>
		<form action="{{ url_for('sala.sala', id_sala=sala_id, nome_sala=sala_nome) }}" method="post">
				 <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
				<label for="senha">Senha</label>
				<input type="password" name="senha" id="senha">
            <button class="btn waves-effect waves-light red darken-4" type="submit">Entrar
                <i class="material-icons right">send</i>
            </button>
		</form>
	</div>
{% endblock %}